<footer>
  <div class="container2">
    <div class="footer-section">
      <h3>Job</h3>
      <p>Join us to explore exciting opportunities, enhance your skills, and take the next step towards a fulfilling professional journey.</p>
    </div>

    <div class="footer-section">
      <h3>Company</h3>
      <ul>
        <li><a href="about.php">About Us</a></li>
        <li><a href="about.php#group-info-id">Our Team</a></li>
        <li><a href="">Partners</a></li>
        <li><a href="jobs.php">For Candidates</a></li>
        <li><a href="apply.php">For Employers</a></li>
      </ul>
    </div>

    <div class="footer-section">
      <h3>Job Categories</h3>
      <ul>
        <li><a href="">Telecommunications</a></li>
        <li><a href="">Hotels & Tourism</a></li>
        <li><a href="">Construction</a></li>
        <li><a href="">Education</a></li>
        <li><a href="">Financial Services</a></li>
      </ul>
    </div>

    <div class="footer-newsletter">
      <h3>Newsletter</h3>
      <p>Don't miss out on valuable resources that can help you achieve your professional goals.</p>
      <label for="newsletter-email" class="visually-hidden">Enter your email</label>
      <input type="email" id="newsletter-email" placeholder="Enter your email...">
      <button type="submit" class="subscribe">Subscribe now</button>
    </div>
  </div>
</footer>
</body>
</html>