<header>
  <nav class="navbar">
    <div class="container">
      <div class="navdiv">
        <a href="index.php" class="nav-brand">Job Portal</a>
        <div class="navbar-div">
          <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="about.php">About Us</a></li>
            <li><a href="enhancements.php">Enhancements</a></li>
            <a href="" class="login">Login</a>
            <button id="nav-button"><a href="TBA">Register</a></button>
          </ul> 
        </div>
      </div>
      <div class="pagename">
        <h1><?php echo $pageTitle; ?></h1>
      </div>
    </div>
  </nav>
</header>